name: Python test

on: pull_request

jobs:
  test_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v4

      - name: Build Docker Image
        run: docker build -f Dockerfile.test -t app-estadisticas-tests .

      - name: Run Test inside Docker
        run: docker run --rm app-estadisticas-tests

  test_linux:
    runs-on: ubuntu-latest

    steps:
      # 1. Llevar el código a la máquina virtual
      - name: Descargar Codigo
        uses: actions/checkout@v4

      # 2. Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Dependencias
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requerimientos.txt
          python -m pip install pytest pytest-cov

      - name: Ejecutar pytest y guardar salida
        # Guardamos la salida de pytest en un archivo para poder subirla como artifact.
        # Usamos `set -o pipefail` para que el paso falle si pytest falla,
        # pero el archivo seguirá existiendo y podrá subirse en el paso `if: always()`.
        run: |
          pytest -v --cov=src --cov-report=html

  test_windows:
    runs-on: windows-latest

    steps:
      # 1. Llevar el código a la máquina virtual
      - name: Descargar Codigo
        uses: actions/checkout@v4

      # 2. Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requerimientos.txt
          pip install pytest pytest-cov

      - name: Ejecutar pytest y guardar salida
        # En Windows usamos PowerShell; redirigimos salida y la guardamos con Tee-Object.
        # `exit $LASTEXITCODE` asegura que el paso devuelva el código de pytest.
        shell: pwsh
        run: |
          pytest --cov=src --cov-report=html
