name: Python test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Dependencias
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          python -m pip install pytest pytest-cov

      - name: Ejecutar pytest
        run: pytest --cov=src --cov-report=html
